%% MAIN ECU initialization
% Initialization of all the variables in the main ECU model

%% Type definitions
Simulink.defineIntEnumType('PowerModes', ... 
    {'StartUp',  'Idle', 'RTD', 'Faulted', 'Stopped', 'Undefined'}, ...
    [0; 1; 2; 4; 8; 255], ... 
    'Description', 'Power Modes', ...
    'DefaultValue', 'Undefined', ...
    'HeaderFile', 'powermodes.h', ...
    'DataScope', 'Exported', ...
    'AddClassNameToEnumNames', true, ...
    'StorageType', 'uint8');

Simulink.defineIntEnumType('IgnitionStatus', ... 
    {'KeyNotPresent',  'KeyPresent', 'Ignition', 'NonInitialized', 'Undefined'}, ...
    [0; 1; 2; 4; 255], ... 
    'Description', 'Ignition Status', ...
    'DefaultValue', 'Undefined', ...
    'HeaderFile', 'status.h', ...
    'DataScope', 'Exported', ...
    'AddClassNameToEnumNames', true, ...
    'StorageType', 'uint8');

Simulink.defineIntEnumType('AInStatus', ... 
    {'Ok', 'STB', 'STG', 'Implausible', 'Undefined'}, ...
    [0; 1; 2; 4; 255], ... 
    'Description', 'Analog Input status', ...
    'DefaultValue', 'Undefined', ...
    'HeaderFile', 'status.h', ...
    'DataScope', 'Exported', ...
    'AddClassNameToEnumNames', true, ...
    'StorageType', 'uint8');

Simulink.defineIntEnumType('DInStatus', ... 
    {'Ok', 'UnderValue', 'OverValue', 'MidValue', 'Undefined'}, ...
    [0; 1; 2; 4; 255], ... 
    'Description', 'Digital input status', ...
    'DefaultValue', 'Undefined', ...
    'HeaderFile', 'status.h', ...
    'DataScope', 'Exported', ...
    'AddClassNameToEnumNames', true, ...
    'StorageType', 'uint8');

Simulink.defineIntEnumType('MsgStatus', ... 
    {'Ok', 'TimedOut', 'Undefined'}, ...
    [0; 1; 255], ... 
    'Description', 'Message status', ...
    'DefaultValue', 'Undefined', ...
    'HeaderFile', 'status.h', ...
    'DataScope', 'Exported', ...
    'AddClassNameToEnumNames', true, ...
    'StorageType', 'uint8');

%% Initialization scripts
calibration_init;
indicators_init;
maincanrx_init;
wheelspeedsim_init;