<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Root>
	<ProjectExperiment>
		<artifacts/>
		<viewflags>
			<Name type="key">MainECUTest.CDP</Name>
			<ViewFlags type="key">1</ViewFlags>
			<item>
				<Name type="key">MainECUTest</Name>
				<ViewFlags type="key">1</ViewFlags>
				<item>
					<Name type="key">Specifications</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Project Plans</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Global Data Sets</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Variable Descriptions</Name>
					<ViewFlags type="key">0</ViewFlags>
					<item>
						<Name type="key">MainECUTest.vdb</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
					<item>
						<Name type="key">mainecu.sdf</Name>
						<ViewFlags type="key">0</ViewFlags>
						<item>
							<Name type="key">mainecu.trc</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
						<item>
							<Name type="key">mainecu.map</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
						<item>
							<Name type="key">mainecu.ppc</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
						<item>
							<Name type="key">mainecu.trz</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
					</item>
				</item>
				<item>
					<Name type="key">Data Sets</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Variable Filters</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Label Lists</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Global Devices</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Python Scripts</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">BusNavigator</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Signal Description Sets</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
			</item>
			<item>
				<Name type="key">Events</Name>
				<ViewFlags type="key">1</ViewFlags>
				<item>
					<Name type="key">Project.events</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
			</item>
		</viewflags>
	</ProjectExperiment>
</Root>